

def total_sales (orders_report):
    """This function will calculate the revenue by type of melon and provide quantities sold.
        takes the order report as an argument"""
    log_file = open (orders_report)
    melon_tallies = {"Musk":0, "Hybrid":0, "Watermelon":0, "Winter": 0}

    for line in log_file:
        data = line.split("|")
        melon_type = data[1]
        melon_count = int(data[2])
        melon_tallies[melon_type] += melon_count

        
     
    melon_prices = { "Musk": 1.15, "Hybrid": 1.30, "Watermelon": 1.75, "Winter": 4.00 }
    total_revenue = 0
    for melon_type in melon_tallies:
        price = melon_prices[melon_type]
        revenue = price * melon_tallies[melon_type]
        total_revenue += revenue
        # print "We sold %data %s melons at %0.2f each for a total of %0.2f" % (melon_tallies[melon_type], melon_type, price, revenue)
    
    log_file.close()
    print "TOTAL SALES:"
    print"We sold {} {} melons at {:.2f} each for a total of {:.2f}".format(melon_tallies[melon_type], melon_type, price, revenue)
        
def comm_sales (sales_report):
    """This function will show how much was generated by sales people and how much from internet sales.
        takes the sales report as an argument"""
    log_file = open(sales_report)
    sales = [0, 0]


    for line in log_file:
        data = line.split("|")
        if data[1] == "0":
            sales[0] += float(data[3])
        else:
            sales[1] += float(data[3])
    print "SALES INFORMATION"
    print "Salespeople generated ${:.2f} in revenue.".format(sales[1])
    print "Internet sales generated ${:.2f} in revenue.".format(sales[0])


    if sales[1] > sales[0]:
        print "Guess there's some value to those salespeople after all."
    else:
        print "Time to fire the sales team! Online sales rule all!"

    log_file.close

total_sales("orders-by-type.txt")

comm_sales("orders-with-sales.txt")